apiVersion: v1 
kind: Service
metadata: 
  name: frontend-service
spec:
  selector: 
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80   #you can use any port it is out side port
      targetPort: 80  #here you need use the port that exposed by docker file(here service docker file)
      