apiVersion: v1 
kind: Service
metadata: 
  name: tasks-service
spec:
  selector: 
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000   #you can use any port it is out side port
      targetPort: 8000  #here you need use the port that exposed by docker file(here service docker file)
      