apiVersion: v1 
kind: Service
metadata: 
  name: users-service
spec:
  selector: 
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080   #you can use any port it is out side port
      targetPort: 8080  #here you need use the port that exposed by docker file(here service docker file)
      